### PR TITLE
add country name acronym/aliases lookup json

### PR DESCRIPTION
**Pull request by yash1994**
Hi @NirantK ,

I stumbled upon your work today via [COVID-19 Tracker](https://www.covid19india.org/). Great work! Hoping to be helpful for the cause, so created a commonly used country name (~140 countries) acronyms/aliases lookup JSON from Wikipedia with common name as key and acronyms/aliases as values in `data` directory.

### CODE REVIEW

**Comment by NirantK** [comment]
This is fantastic @yash1994! Thank you so much. 

Can you consider adding a reverse json as well?
```javascript
[{"UK": "United Kingdom"}]
```

In addition to what you have?

**Comment by yash1994** [comment]
I've added a flattened JSON object as well in the same file separated by the new line.

**Comment by rohanrmallya** [comment]
Hi @yash1994, the flattened JSON is awesome! Do you think we could use that as a python list and potentially solve #14 ? 😃

**Comment by yash1994** [comment]
Yes, both structures (python list lookup and flat dictionary lookup) are there in JSON file.

**Comment by meghanabhange** [comment]
Hey,

@yash1994 The JSON currently is hard to read because it throws an error `JSONDecodeError` because of there are multiple JSON root elements

Would it be possible to split the JSON in two different JSONs? (country to acronym/aliases and acronym/aliases  to country)

**Comment by yash1994** [comment]
Hi,
created separate JSON files for both the objects.

**Comment by meghanabhange** [comment]
Perfect :))

**Pull request merged**
