### PR TITLE
Cleanup, validation and decoupling

### PR DESCRIPTION
**Pull request by vcidst**
Hey Nirant,

These should have been individual PRs but I did this in a hurry, let me know what you think

1. Cleaned up the folder structure. All notebooks into`\notebooks`, CSV files in `\data`
2. Decoupled spacy NLP with the flask server
3. Added validation to Flask Request
4. Using `jsonify()`

### CODE REVIEW

**Comment by vcidst** [comment]
Forgot to mention I also moved the API documentation to `readme.md`

**Comment by NirantK** [comment]
> Decoupled spacy NLP with the flask server

Cannot have separate files right now. Those are harder to sync between here and PythonAnywhere.

**Comment by NirantK** [comment]
If you could raise a PR with the other changes, I'd be happy to merge that.

**Comment by vcidst** [comment]
Fair, I'll raise another PR

**Pull request closed without merging**
